[package]
name = "azusa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
reqwest = { version = "*", features = ["native-tls-vendored"] }
tokio = { version = "1", features = ["full"]}

[dev-dependencies]
http = "*"
