[package]
name = "azusa"
version = "0.1.0"
authors = ["techno-tanoC <develop.tanoc@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.4"
tokio = { version = "0.2.18", features = ["full"] }
tokio-util = { version = "0.3.1", features = ["compat"] }
reqwest = { version = "0.10.4", features = ["stream", "native-tls-vendored"] }
serde = { version = "1.0.106", features = ["derive"] }
serde_json = "1.0.50"
indexmap = "1.3.2"
uuid = { version = "0.8.1", features = ["v4"]}
tempfile = "3.1.0"
warp = "0.2.2"
log = "0.4.8"
log4rs = "0.11.0"

[dev-dependencies]
http = "0.2.1"
