services:
  app:
    build:
      context: ./
      dockerfile: docker/release/Dockerfile
    image: registry.gitlab.com/techno-tanoc/azusa:0.2.0
    environment:
      CERT: /workspace/cert
      VOLUME: /workspace/volume
    init: true
    platform: linux/x86_64
    ports:
      - "3333:3000"
    volumes:
      - ./volume:/workspace/volume
      - ./cert:/workspace/cert
