services:
  app:
    build:
      context: ../
      dockerfile: docker/server/Dockerfile
    command: sleep infinity
    environment:
      VOLUME: ./volume
    init: true
    volumes:
      - ../:/workspace:delegated
      - cargo:/usr/local/cargo:delegated
      - target:/workspace/target:delegated

volumes:
  cargo:
  target:
