refresh_rate: 30 seconds

appenders:
  stdout:
    kind: console

  file:
    kind: file
    path: ./log/azusa.log

  lib:
    kind: file
    path: ./log/library.log

root:
  level: info
  appenders:
    - file

loggers:
  azusa:
    level: info
    appenders:
      - stdout

  hyper:
    level: info
    appenders:
      - lib
    additive: false

  reqwest:
    level: debug
    appenders:
      - lib
    additive: false
