name: Rust

on:
- push
- pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    container: rust:1.42.0-slim-buster
    steps:
    - uses: actions/checkout@v2
    - name: install libssl-dev
      run: apt update && apt install -y libssl-dev pkg-config
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
