name: Rust

on:
- push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [1.42.0, nightly]
    steps:
    - uses: actions/checkout@v2

    - name: Install rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
        components: rustfmt, clippy

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: 7RG6TuEsctxa4-cargo-${{ matrix.os }}-${{ matrix.rust }}-${{ hashFiles('**/Cargo.lock') }}

    - name: tests
      uses: actions-rs/cargo@v1
      with:
        toolchain: ${{ matrix.rust }}
        command: test
        args: --all
